# Generated by Django 3.2.5 on 2021-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=100)),
                ('slot', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
